# Generated by Django 5.1.1 on 2024-09-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.PositiveIntegerField(default=0, max_length=4),
        ),
    ]
