# Generated by Django 5.1.1 on 2024-09-28 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, null=True, verbose_name='enter title')),
                ('image', models.ImageField(db_index=True, null=True, upload_to='tv_show/')),
                ('description', models.TextField(db_index=True, null=True, verbose_name='write description')),
                ('genre', models.CharField(choices=[('Ужасы', 'Ужасы'), ('Комедия', 'Комедия'), ('Фантастика', 'Фантастика')], db_index=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField(db_index=True, null=True, verbose_name='write price')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_movie', models.TextField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('movie_review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_movie', to='tv_show.movie')),
            ],
        ),
    ]
