# Generated by Django 5.1.1 on 2024-09-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='enter title')),
                ('image', models.ImageField(upload_to='book/', verbose_name='download picture')),
                ('description', models.TextField(verbose_name='write description')),
                ('genre', models.TextField(verbose_name='write genres')),
                ('author', models.TextField(verbose_name='write author name')),
                ('price', models.PositiveIntegerField(verbose_name='write price')),
                ('like_or_dislike', models.CharField(choices=[('👍🏻', '👍🏻'), ('👎🏻', '👎🏻')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
