# Generated by Django 5.1.1 on 2024-09-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='like_or_dislike',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[(1, 'Детектив'), (2, 'Фантастика'), (3, 'Детская литература'), (4, 'Психология'), (5, 'Кулинария')], max_length=100, null=True),
        ),
    ]
