# Generated by Django 5.1.1 on 2024-09-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_like_or_dislike_alter_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(null=True, verbose_name='write number of pages'),
        ),
        migrations.AddField(
            model_name='book',
            name='url_book',
            field=models.URLField(null=True, verbose_name='write book url'),
        ),
    ]
