# Generated by Django 5.1.1 on 2024-09-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_reviewbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Детектив'), (2, 'Фантастика'), (3, 'Детская литература'), (4, 'Психология'), (5, 'Кулинария')], null=True, verbose_name='Genre'),
        ),
    ]
