# Generated by Django 5.1.1 on 2024-09-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
