# Generated by Django 5.1.1 on 2024-09-27 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_book_created_at_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(db_index=True, null=True, verbose_name='write author name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(db_index=True, null=True, verbose_name='write description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Детектив', 'Детектив'), ('Психология', 'Психология'), ('Детская литература', 'Детская литература')], db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(db_index=True, null=True, upload_to='book/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(db_index=True, null=True, verbose_name='write number of pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(db_index=True, null=True, verbose_name='write price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url_book',
            field=models.URLField(db_index=True, null=True, verbose_name='write book url'),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='book_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_book', to='book.book'),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='text_book',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
